include:
  - https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools/-/raw/main/gsi-port-ci.yml

variables:
  BUILD_DEVEL_FLASHABLE_FOCAL: 1
  ROOTFS_URL: "https://ci.ubports.com/job/ubuntu-touch-rootfs/job/main/244/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz"
  OTA_CHANNEL: "20.04/arm64/android9plus/devel"

build:
  tags: [ubports]

devel-flashable:
  allow_failure: true
